name: glukel
favicon: null
layout_spectrum: 0.6602830928750336
typography_spectrum: 0.03392641246318817
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7644549559336156
  lightness: 0.04414387629367411
  saturation: 0.12081323354505002
  rhythmicContrast: 0.1052647796459496
purpose: []
